### ISSUE TITLE
Test(s) failing

### ISSUE THREAD

**Issue by Aniket-Pradhan** [aflc/editdistance#40]
Thanks for the amazing package!

I am trying to package this tool for Fedora, however, the test provided by you is failing for some reason. Can you help me diagnose the issue?

I am simply using disutils to build and install the package, like this:
```
python setup.py build
python setup.py install
```
The package installs correctly. However, when I run the test (using `nose`), I get the following test failed error:
```
$ nosetests test/

ERROR: test_editdistance (test_editdistance.TestEditDistance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/major/Desktop/editdistance/test/test_editdistance.py", line 5, in test_editdistance
    import editdistance
  File "/home/major/Desktop/editdistance/editdistance/__init__.py", line 1, in <module>
    from .bycython import eval
ModuleNotFoundError: No module named 'editdistance.bycython'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
```

Can you help me in finding out the issue here?
**P.S.** I am using a virtualenv for building/installing the module.

**Comment by Aniket-Pradhan** [comment]
I have gcc and glibc installed as well.

I am not well-versed with c-python, so I am unable to guess the issue, but am I correct to guess that the issue might be an incorrect flag is being passed during installation?

**Comment by Aniket-Pradhan** [comment]
Update

When I run `python setup.py test` it does this:
```
running test
running egg_info
writing editdistance.egg-info/PKG-INFO
writing dependency_links to editdistance.egg-info/dependency_links.txt
writing top-level names to editdistance.egg-info/top_level.txt
reading manifest file 'editdistance.egg-info/SOURCES.txt'
writing manifest file 'editdistance.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/editdistance/bycython.cpython-37m-x86_64-linux-gnu.so -> editdistance

----------------------------------------------------------------------
Ran 0 tests in 0.000s
```

After this, when I run `nosetests test/` the testcase passes. Is this how I am supposed to run the test? 
It also gives out this warning:
```
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
```

**Comment by Aniket-Pradhan** [comment]
Simply had to set the PYTHONPATH to editdistance/editdistance to run the tests correctly. Hope this is a correct solution to the problem. :P
