### ISSUE TITLE
Unable to use editdistance on Mac

### ISSUE THREAD

**Issue by pengyu** [aflc/editdistance#7]
I got the follow error on Mac. Does anybody know how to fix the problem? Thanks.

```
~$ pip install  --upgrade editdistance
~$ ./main.py 
Traceback (most recent call last):
  File "./main.py", line 4, in <module>
    import editdistance
  File "/Users/u/Library/Python/2.7/lib/python/site-packages/editdistance/__init__.py", line 1, in <module>
    from .bycython import eval
ImportError: dlopen(/Users/u/Library/Python/2.7/lib/python/site-packages/editdistance/bycython.so, 2): no suitable image found.  Did find:
    /Users/u/Library/Python/2.7/lib/python/site-packages/editdistance/bycython.so: mach-o, but wrong architecture
```

**Comment by fhamborg** [comment]
Same here

**Comment by aflc** [comment]
I introduced binary wheels for Mac!
